<?xml version="1.0" encoding="UTF-8"?>
<definitions name="homesys"
 targetNamespace="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl"
 xmlns:tns="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:ns="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<!-- getCurrentTime -->
<message name="getCurrentTimeRequest">
</message>

<message name="getCurrentTimeResponse">
 <part name="time" type="xsd:string"/>
</message>


<portType name="homesysPortType">
 <operation name="getCurrentTime">
  <documentation>Service definition of function ns__getCurrentTime</documentation>
  <input message="tns:getCurrentTimeRequest"/>
  <output message="tns:getCurrentTimeResponse"/>
 </operation>
</portType>

<binding name="homesys" type="tns:homesysPortType">
 <SOAP:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="getCurrentTime">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="http://adjserwer.dyndns.org/soap_server/webservice/homesys.wsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="homesys">
 <documentation>gSOAP 2.7.9k generated service definition</documentation>
 <port name="homesys" binding="tns:homesys">
  <SOAP:address location="http://adjserwer.dyndns.org:1234"/>
 </port>
</service>

</definitions>
